name: Update Graph README.md

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour at the start of the hour

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Graph.sh Script
        run: ./Graph.sh
